---
- name: Add Nginx repo
  become: true
  ansible.builtin.template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    mode: '0644'

- name: Install Nginx and Unzip
  become: true
  ansible.builtin.yum:
    name:
      - nginx
      - unzip
    state: present

- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{ document_root }}"
    state: directory
    mode: '0755'

- name: Unarchive Lighthouse archive
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip
    dest: "{{ document_root }}"
    remote_src: true
    setype: httpd_sys_content_t

- name: Apply Nginx template
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: '0644'
#  notify: Restart Nginx
